### ISSUE TITLE
Free monad refactoring observations

### ISSUE THREAD

**Issue by moodmosaic** [blackheaven/HaskellKata-RestaurantReservation#1]
In the original [gist](https://gist.github.com/ploeh/c999e2ae2248bd44d775), `checkCaravanCapacityOnError` has the type signature:

``` haskell
checkCaravanCapacityOnError :: Error
                            -> Maybe Caravan
                            -> Reservation
                            -> Either Error Reservation
```

Though, currently the refactored version in this repository changes the type signature and function name to:

``` haskell
checkCaravanCapacity :: Reservation
                     -> Caravan
                     -> Either Error Reservation
```

I'd expect that the types and functions in the `ApiModel` wouldn't change by the free monad refactoring.

---

IIUIC, the _current_ free monad refactoring expects that the original `checkCaravanCapacityOnError` returns a tuple of a `Caravan` and a `Reservation`, like so:

``` haskell
checkCaravanCapacityOnError :: Error
                            -> Maybe Caravan
                            -> Reservation
                            -> Either Error (Caravan, Reservation)
```

This can be double-checked if I make the changes in the `App.hs` below:

``` diff
diff --git a/src/App.hs b/src/App.hs
index 4d313cd..5fef54c 100644
--- a/src/App.hs
+++ b/src/App.hs
@@ -16,8 +16,7 @@ svcAddr = "."
 tryRentCaravan :: Reservation -> CaravanServiceAction (Either Error Reservation)
 tryRentCaravan reservation = do
   foundCaravan <- findCaravan (quantity reservation) (date reservation)
-  let eitherCaravan = maybeToEither CapacityExceeded id foundCaravan
-  let newRes = eitherCaravan >>= \c -> ((\ r -> (c, r)) <$> checkCaravanCapacity reservation c)
+  let newRes = checkCaravanCapacityOnError CapacityExceeded foundCaravan reservation
   either (return . Left) (\(c, r) -> (reserveCaravan (date r) c >> return (return r))) newRes

 postReservation :: ReservationRendition -> IO (HttpResult ())
```

---

AFAICT, this repository does a general refactoring, _including a free monad one_. – What do I miss? :smiley:

**Comment by blackheaven** [comment]
Thanks for your answer. 
Sure, I did three things in that order (sadly I didn't make the relevant commits):
- Taking away controlflow of the domain code 
- Splitting code into files according to their "subdomain" (IO actions is not relevant in our case) 
- Introducing free monads for the two subdomains

I think your comment is focused on my first action. 
`checkCaravanCapacity` and Al should not depend on previous call directly, it reduces their composability.
It's the role of the monadic functions to take care of controlflow combination. 
You should assert that if a function is called, there is a reason.
I can easily imagine that I just want to check if I can put a couple in my caravan because they want intimacy or a group of students because they will make noise, etc. even if my main room is not full (so I have no error to give).
About the double check, currently it's more a hack due to the miss of mtl.

I hope I was clear (I don't miss your point), I think you figured out all the things I've done. 
Anyway, don't hesitate to comment more, criticise and so on. 
I'll integrate mtl soon.

**Comment by moodmosaic** [comment]
Thank you for the thorough answer! If we're reaching the point where we'd need `mtl`, shouldn't we start considering [effects and handlers](http://homepages.inf.ed.ac.uk/slindley/papers/handlers.pdf) (as an alternative)?
